### ISSUE TITLE
Formatting of Mstest results

### ISSUE THREAD

**Issue by Lowry99** [reportunit/reportunit#8] opened 2015-08-05 10:26 UTC
Running latest version with MStest output from 2010

![image](https://cloud.githubusercontent.com/assets/12037104/9083695/4a5e7ec0-3b64-11e5-9a93-82d9abbed967.png)

If you can provide me a email/ftp etc I can send over the .TRX file

**Comment by anshooarora** [comment] 2015-08-05 13:28
Please send the file to anshooarora@gmail.com.

**Comment by anshooarora** [comment] 2015-08-05 13:56
Please send the file to anshooarora@gmail.com.

What browser are you using?  Can you try this on a different browser and let me know if its the same there?

**Comment by anshooarora** [comment] 2015-08-06 14:02
Matthew - I am able to reproduce this.  The issue is because in the TRX file, there are a lot of times the word <code>&lt;table&gt;</code> appears.  In HTML, it looks like lower-than and greater-than but in XML it would look like:

```
&lt;table&gt;
```

Is this data being generated automatically?  What I did was, opened the TRX file, replaced all instances of the above string with <code>[table]</code> and it works properly.  Please try with the following file and let me know if it works:

http://relevantcodes.com/Tools/ReportUnit/ReportUnitLTGTFix.zip

**Comment by Lowry99** [comment] 2015-08-06 14:12
Hey! 

That seems to of sorted out. Really appreciate the help!
The Trx is auto generated from out tests integrated into out build process but I can write a script to amend the file. 
Thanks a lot!

**Comment by anshooarora** [comment] 2015-08-06 14:22
Yes, the error was due to the following string only then:

```
&lt;table&gt;
```

If you can parse this out and replace with <code>[table]</code> or any safe tags before the report is generated, you won't see this issue..  

Closing ticket as issue resolved with the new executable.

**Closed by anshooarora** 2015-08-06 14:22 UTC
